package stringen;

public enum ALevelSubject {
    ANCIENT_HISTORY("ANCIENT HISTORY", "20"),
    APPLIED_MATHEMATICS("APPLIED MATHEMATICS", "22"),
    ARABIC_LANGUAGE_AND_LITERATURE("ARABIC LANGUAGE AND LITERATURE", "40"),
    ART("ART", "14"),
    ART_AND_DESIGN("ART & DESIGN", "84"),
    BAHASA_MALAYSIA_MALAY("BAHASA MALAYSIA/MALAY", "71"),
    BENGALI("BENGALI", "80"),
    DIVINITY("BIBLE KNOWLEDGE/DIVINITY", "02"),
    BIOLOGY("BIOLOGY", "11"),
    BOTANY("BOTANY", "12"),
    CHEMISTRY("CHEMISTRY/ADD. CHEMISTRY", "09"),
    CHINA_STUDIES_CHINESE("CHINESE STUDIES IN CHINESE", "87"),
    CHINA_STUDIES_ENGLISH("CHINESE STUDIES IN ENGLISH", "86"),
    CHINESE("CHINESE", "17"),
    CHINESE_SECOND_LANGUAGE("CHINESE AS SECOND LANGUAGE", "46"),
    CHINESE_B("CHINESE B", "4"),
    CHINESE_LANGUAGE_LITERATURE("CHINESE LANGUAGE & LITERATURE", "88"),
    CHINESE_LITERATURE("CHINESE LITERATURE", "43"),
    CLASSICAL_ARABIC("CLASSICAL ARABIC", "27"),
    COMMERCIAL_LAW("COMMERICAL LAW", "38"),
    COMPUTING("COMPUTER SCIENCE/COMPUTING", "61"),
    ECONOMICS("ECONOMOICS", "05"),
    EKONOMI("EKONOMI", "72"),
    ENGLISH_SECOND_LANGUAGE("ENGLISH AS SECOND LANGUAGE", "47"),
    ENGLISH_LANGUAGE_AND_LINGUISTICS("ENGLISH LANGUAGE AND LINGUISTICS", "58"),
    ENGLISH_LITERATURE("ENGLISH LITERATURE", "83"),
    ENGLISH("ENGLISH/ENGLISH USAGE", "01"),
    FRENCH("FRENCH", "19"),
    FRENCH_SECOND_LANGUAGE("FRENCH AS SECOND LANGUAGE", "50"),
    FURTHER_MATHEMATICS("FURTHER MATHEMATICS", "07"),
    GENERAL_PAPER("GENERAL PAPER", "GP"),
    GENERAL_STUDIES_CHINESE("GENERAL STUDIES IN CHINESE", "82"),
    GEOGRAPHY("GEOGRAPHY", "04"),
    GEOLOGY("GEOLOGY", "18"),
    GEOMETRICAL_AND_BUILDING_DRAWING("GEOMETRICAL & BUILDING DRAWING", "29"),
    GEOMETRICAL_AND_MECH_DRAWING("GEOMETRICAL & MECH DRAWING", "28"),
    GERMAN("GERMAN", "77"),
    GERMAN_SECOND_LANGUAGE("GERMAN AS SECOND LANGUAGE", "51"),
    GUJARATI("GUJARATI", "53"),
    HIGHER_CHINESE("HIGHER CHINESE", "1"),
    HIGHER_MALAY("HIGHER MALAY", "2"),
    HIGHER_TAMIL("HIGHER TAMIL", "3"),
    HINDI("HINDI", "54"),
    HISTORY("HISTORY", "03"),
    HISTORY_CHINESE("HISTORY (CHINESE)", "85"),
    ILMU_ALAM("ILMU ALAM", "73"),
    ILMU_HISAB("ILMU HISAB", "74"),
    INDIA_STUDIES("INDIA STUDIES", "57"),
    ISLAMIC_LAW("ISLAMIC LAW", "41"),
    ISLAMIC_STUDIES("ISLAMIC STUDIES", "26"),
    ISLAMIC_THEOLOGY("ISLAMIC THEOLOGY", "42"),
    JAPANESE("JAPANESE", "78"),
    JAPANESE_SECOND_LANGUAGE("JAPANESE AS SECOND LANGUAGE", "52"),
    MALAY_LITERATURE("KESUSATERAAN MELAYU/MALAY LITERATURE", "81"),
    KNOWLEDGE_AND_INQUIRY("KNOWLEDGE & INQUIRY", "KI"),
    LATIN("LATIN", "24"),
    LITERATURE_ENGLISH("LITERATURE IN ENGLISH", "56"),
    LUKISAN("LUKISAN", "75"),
    MALAY("MALAY", "8"),
    MALAY_SECOND_LANGUAGE("MALAY AS SECOND LANGUAGE", "48"),
    MALAY_B("MALAY B", "5"),
    MALAY_LANGUAGE_AND_LITERATURE("MALAY LANGUAGE & LITERATURE", "89"),
    MANAGEMENT_OF_BUSINESS("MANAGEMENT OF BUSINESS", "59"),
    MATHEMATICS("MATHEMATICS", "06"),
    METAL_WORK("METAL WORK", "30"),
    MUSIC("MUSIC", "15"),
    NTU_CONTEMPORARY_PHYSICS("NTU CONTEMPORARY PHYSICS", "69"),
    NTU_MOLECULAR_BIOLOGY("NTU MOLECULAR BIOLOGY", "67"),
    NTU_NUMBERS_AND_MATRICES("NTU NUMBERS & MATRICES", "65"),
    NTU_ORGANIC_SYNTHESIS_AND_MECHANISM("NTU ORGANIC SYNTHESIS & MECHANISM", "68"),
    NTU_SCIENCE_RESEARCH("NTU SCIENCE RESEARCH", "96"),
    NTU_SEMICONDUCTOR_PHYSICS_AND_DEVICES("NTU SEMICONDUCTOR PHYSICS & DEVICES", "70"),
    NTU_A_STAR_HCI_SCIENCE_RESEARCH("NTU-A*STAR-HCI SCIENCE RESEARCH", "91"),
    NUS_ECONOMY_AND_SPACE("NUS ECONOMY AND SPACE", "62"),
    NUS_LINEAR_ALGEBRA("NUS LINEAR ALGEBRA", "66"),
    NUS_A_STAR_NJC_SCIENCE_RESEARCH("NUS-A*STAR-NJC SCIENCE RESEARCH", "92"),
    NUS_A_STAR_RJC_SCIENCE_RESEARCH("NUS-A*STAR-RJC SCIENCE RESEARCH", "93"),
    NUS_A_STAR_VJC_SCIENCE_RESEARCH("NUS-A*STAR-VJC SCIENCE RESEARCH", "94"),
    NUS_MOE_HUMANITIES_AND_SOC_SCI_RESEARCH("NUS-MOE HUMANITIES * SOC SCI RESEARCH", "64"),
    NUS_MOE_SCIENCE_RESEARCH("NUS-MOE SCIENCE RESEARCH", "95"),
    NUS_GEOPOLITICS_WAR_AND_PEACE("NUS GEOPOLITICS: WAR AND PEACE", "60"),
    O_LEVEL_ADDITIONAL_MATHEMATICS("O-LEVEL ADDITIONAL MATHEMATICS", "99"),
    OFF_ADMIN_AND_SH("OFF ADMIN & SH/TP DUTIES/STENO", "36"),
    OFF_ADMIN("OFF ADMIN/PRIN & PRACTICE OF OFF ADMIN", "35"),
    OTHER_SIL_SUBJECT("OTHER SIL SUBJECT", "SL"),
    OTHER_SUBJECT("OTHER SUBJECT", "00"),
    PHYSICS_WITH_CHEMISTRY("PHYSICS WITH CHEMISTRY/PHY SCI", "10"),
    PHYSICS("PHYSICS/ADD. PHYSICS", "08"),
    MGT_OF_BUSINESS("PR OF MGT & COMM LAW/MGT OF BUSINESS", "45"),
    PRIN_OF_MGMT_AND_ECON_STRU_AND_ORG("PRIN OF MGMT & ECON STRU & ORG", "33"),
    PRINCIPLES_OF_ACCOUNTING("PRINCIPLES OF ACCOUNTING", "32"),
    PROJECT_WORK("PROJECT WORK", "PW"),
    PUNJABI("PUNJABI", "25"),
    PURE_MATHEMATICS("PURE MATHEMATICS", "21"),
    SEJARAH("SEJARAH", "76"),
    SHORTHAND_AND_TYPING("SHORTHAND AND TYPING", "34"),
    SMU_GAME_THEORY_AND_COMPETITION("SMU GAME THEORY AND COMPETITION", "63"),
    STATISTICS("STATISTICS", "39"),
    STRUC_AND_WORKING_OF_BRITISH_GOVT("STRUC & WORKING OF BRITISH GOVT.", "37"),
    TAMIL("TAMIL", "23"),
    TAMIL_SECOND_LANGUAGE("TAMILY AS SECOND LANGUAGE", "49"),
    TAMIL_B("TAMIL B", "6"),
    TAMIL_LANGUAGE_AND_LITERATURE("TAMIL LANGUAGE & LITERATURE", "90"),
    THEATRE_STUDIES_AND_DRAMA("THEATRE STUDIES & DRAMA", "79"),
    URDU("URDU", "55"),
    WOODWORK("WOODWORK", "31"),
    WORLD_AFFAIRS("WORLD AFFAIRS SINCE 1945", "44"),
    ZOOLOGY("ZOOLOGY", "13");

    String name;
    String subjectCode;

     ALevelSubject(String name, String subjectCode) {
        this.name = name;
        this.subjectCode = subjectCode;
    }

    public String getName() {
         return name;
    }

    public String getSubjectCode() {
         return subjectCode;
    }

    public static ALevelSubject getSubject(String subjectName) {
        for (ALevelSubject subject: values()) {
            if (subject.getName().equals(subjectName)) {
                return subject;
            }
        }
        throw new IllegalArgumentException();
    }

}
